name: Build and deploy .NET Core application to Function App content-function1

on:
  push:
    branches:
      - main

env:
  AZURE_FUNCTIONAPP_NAME: content-function1 # The name of your function app in Azure
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'content-function/published' # The path to the published function app
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 8.0.x
  WORKING_DIRECTORY: content-function

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: 'Setup .NET SDK'
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

      - name: 'Restore Dependencies'
        run: dotnet restore "${{ env.WORKING_DIRECTORY }}"

      - name: 'Build Application'
        run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore

      - name: 'Publish Application'
        run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"

      - name: 'Upload Artifact for Deployment'
        uses: actions/upload-artifact@v4
        with:
          name: functionapp
          path: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 'Download Artifact from Build Job'
        uses: actions/download-artifact@v4
        with:
          name: functionapp
          path: .z

      - name: 'Azure Login'
        uses: azure/login@v2
        with:
          creds: ${{ secrets.content_function1_SPN }}

      - name: 'Deploy to Azure Function App'
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: .