name: Build and deploy .NET Core application to Function App content-function1

on:
  push:
    branches:
      - main

env:
  AZURE_FUNCTIONAPP_NAME: content-function1  
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 8.0.x
  WORKING_DIRECTORY: content-function
  # Add runtime identifier for Linux deployment
  RUNTIME_IDENTIFIER: linux-x64

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

    - name: Restore dependencies
      run: dotnet restore "${{ env.WORKING_DIRECTORY }}"

    - name: Build application
      run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore
        
    - name: Publish application
      run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --output ./published

    - name: Verify published structure
      run: |
        ls -R ./published
        [ -d "./published/${{ env.AZURE_FUNCTIONAPP_NAME }}/.azurefunctions" ] || mkdir -p "./published/${{ env.AZURE_FUNCTIONAPP_NAME }}/.azurefunctions"

    - name: Upload artifact for deployment
      uses: actions/upload-artifact@v4
      with:
        name: functionapp
        path: ./published/${{ env.AZURE_FUNCTIONAPP_NAME }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: production
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: functionapp
        path: ./deploy 

    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}

    - name: Deploy to Azure Function App
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ./deploy